= chapper

This is chapper: `<<(.*)>>`

He finds reference IDs in your AsciiDoc files.
He uses those to map out how your sections and chapters reference one another.
Then, you can pipe that map into https://mermaid-js.github.io/mermaid-live-editor[Mermaid.js] to get a graphical representation.

== Installation

Chapper is built using https://deno.land/[Deno] and TypeScript.

In order to build or run tests, you will need Deno installed (see main site -- it's a single binary!).

One (experimental) feature of Deno is the ability to build JS/TS applications as a single binary, so releases of Chapper should (eventually) be able to run without installing Deno.

=== Development

With Deno installed and added to your PATH, build Chapper with:

```
deno compile --unstable --allow-read -o chapper src/index.ts
```

This will build a single binary named `chapper`.

== Usage

Right now, Chapper is very naive in file input handling.
Ideally, you should run it within the `sg-chapters` directory like so:

```
cd path/to/sg-chapters
chapper **/*.adoc
```

This will print all references in Mermaid.js syntax.
Currently, you will likely also get a lot of `WARNING`'s.
Remove those lines before pasting into Mermaid.js (this workflow will be improved).

You can use the Mermaid.js live editor (linked above) in order to render a diagram of the references.

=== Running tests

Chapper includes a number of unit tests, which you can run with `deno test` in the main directory.
