= chapper

This is chapper: `<<(.*)>>`

He finds reference IDs in your AsciiDoc files.
He uses those to map out how your sections and chapters reference one another and outputs GraphViz syntax.
You can paste the output directly into a tool like https://sketchviz.com/new[SketchViz] to generate the image.

== Installation

Chapper is built using https://deno.land/[Deno] and TypeScript.

In order to build or run tests, you will need Deno installed (see main site -- it's a single binary!).

One (experimental) feature of Deno is the ability to build JS/TS applications as a single binary, so releases of Chapper should (eventually) be able to run without installing Deno.

=== Development

With Deno installed and added to your PATH, build Chapper with:

```
deno compile --unstable --allow-read -o chapper src/index.ts
```

This will build a single binary named `chapper`.

== Usage

Right now, Chapper is very naive in file input handling.
Ideally, you should run it within the `sg-chapters` directory like so:

```
cd path/to/sg-chapters
chapper **/*.adoc
```

=== Running tests

Chapper includes a number of unit tests, which you can run with `deno test` in the main directory.
